/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zVmSCoODivq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function status() {
  return (
    <div className="max-w-6xl mx-auto px-4 py-8 sm:px-6 md:py-10">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Student Outpass Requests</h1>
        <div className="flex items-center gap-4">
          <Button variant="outline" size="sm">
            Pending
          </Button>
          <Button variant="outline" size="sm">
            Accepted
          </Button>
        </div>
      </div>
      <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">John Doe</h3>
                <p className="text-sm text-muted-foreground">Visiting family</p>
              </div>
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                Pending
              </Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 3</p>
              <p>Department: Computer Science</p>
              <p>Class: A</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">Jane Smith</h3>
                <p className="text-sm text-muted-foreground">Medical emergency</p>
              </div>
              <Badge className="px-2 py-1 text-xs">Accepted</Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 2</p>
              <p>Department: Biology</p>
              <p>Class: B</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">Michael Johnson</h3>
                <p className="text-sm text-muted-foreground">Family emergency</p>
              </div>
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                Pending
              </Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 4</p>
              <p>Department: Mechanical Engineering</p>
              <p>Class: C</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">Emily Davis</h3>
                <p className="text-sm text-muted-foreground">Attending a conference</p>
              </div>
              <Badge className="px-2 py-1 text-xs">Accepted</Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 1</p>
              <p>Department: Economics</p>
              <p>Class: D</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">David Lee</h3>
                <p className="text-sm text-muted-foreground">Visiting sick relative</p>
              </div>
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                Pending
              </Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 3</p>
              <p>Department: Electrical Engineering</p>
              <p>Class: E</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">Sarah Kim</h3>
                <p className="text-sm text-muted-foreground">Attending a wedding</p>
              </div>
              <Badge className="px-2 py-1 text-xs">Accepted</Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 2</p>
              <p>Department: Psychology</p>
              <p>Class: F</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="text-lg font-medium">Alex Chen</h3>
                <p className="text-sm text-muted-foreground">Attending a funeral</p>
              </div>
              <Badge variant="secondary" className="px-2 py-1 text-xs">
                Pending
              </Badge>
            </div>
            <div className="space-y-1 text-sm text-muted-foreground">
              <p>Year: 4</p>
              <p>Department: Civil Engineering</p>
              <p>Class: G</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Accept
              </Button>
              <Button variant="outline" size="sm">
                Deny
              </Button>
              <Button variant="outline" size="sm">
                Meet Me
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
